README.md, demoscannerapp/build.gradle, demoscannerapp/src/main/AndroidManifest.xml, enioka_scan/build.gradle, enioka_scan_honeywell/build.gradle, enioka_scan_koamtac/build.gradle, enioka_scan_m3/build.gradle, enioka_scan_zebra/build.gradle
Resolves #46 
* Remove mentions of non-existent classes
* Disable lint errors regarding outdated target SDKs
* Add developer quick start section in the README
=> Fix compile errors and add quick start to README

.github/workflows/release.yaml, .github/workflows/test.yaml, README.md
* Fix release workflow trigger: no longer triggers on branch creation or pushes to master
* Fix release naming: now `<tag name>` instead of `Release <tag name>`
* Fix test workflow trigger: no longer triggers on tag pushes (release workflow already contains a test step, no need for duplication)
* Clarify release process in `README.md`: requires manual tag creation only, does not work with manual release creation
=> Fix workflow triggers and clarify release process

enioka_scan/src/main/java/com/enioka/scanner/bt/README.md, enioka_scan/src/main/java/com/enioka/scanner/bt/api/Helpers.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/ScannerProviderResolutionThread.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/SerialBtScannerProvider.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/bleserial/BleDeviceScanner.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/bleserial/BleHelpers.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/bleserial/BleStateMachineDevice.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/bleserial/BleStateMachineGattCallback.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/bleserial/BleSubscriptionType.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/bleserial/BleTerminalIODevice.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/bleserial/BleTerminalIOStreamWriter.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/bleserial/GattAttribute.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/bleserial/GattAttributeType.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/bleserial/package-info.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/classicserial/ClassicBtAcceptConnectionThread.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/classicserial/ClassicBtConnectToDeviceThread.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/classicserial/ClassicBtSocketStreamReader.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/classicserial/ClassicBtSocketStreamWriter.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/classicserial/ClassicBtSocketStreamWriterTask.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/classicserial/ClassicBtSppScanner.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/classicserial/OnStreamConnectedCallback.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/common/BluetoothScannerInternal.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/common/BtConstHelpers.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/common/DataSubscription.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/common/OnConnectedCallback.java, enioka_scan/src/main/java/com/enioka/scanner/bt/manager/common/SerialBtScannerPassiveConnectionManager.java
Refactor the `com.enioka.scanner.bt` package by reorganizing classes and more clearly separating Classic BT from BT Low Energy.
Basically https://github.com/enioka/enioka_scan/tree/ble but more up-to-date with the current repository (the old branch was too disconnected to easily update).
=> Refactor com.enioka.scanner.bt package

enioka_scan/src/main/java/com/enioka/scanner/data/BarcodeType.java, enioka_scan/src/main/java/com/enioka/scanner/sdk/athesi/SPA43LTE/AthesiHHTScanner.java, enioka_scan/src/main/java/com/enioka/scanner/sdk/athesi/SPA43LTE/AthesiHHTSymbology.java
Activate AZTEC as default symbology for SPA43
=> activate AZTEC Symbology on SPA43

enioka_scan/src/main/java/com/enioka/scanner/sdk/zebraoss/ZebraOssScanner.java, enioka_scan/src/main/java/com/enioka/scanner/sdk/zebraoss/commands/ActivateAllSymbologies.java, enioka_scan/src/main/java/com/enioka/scanner/sdk/zebraoss/ssi/SsiCommand.java
When enabling symbologies via scanning a barcode, an unrecognized packet made the library crash. This fix stops the app from crashing and allows use of additional symbologies.
=> Fix ZebraOSS crash triggered by enabling symbologies via barcode

.github/workflows/release.yaml, .github/workflows/test.yaml
Resolves #81 
- `gradle/gradle-build-action` already up-to-date 
- `actions/checkout` upgraded from v2 to v4
- `actions/setup-java` upgraded from v2 to v3
- `action/create-release` and `action/upload-release-asset` are archived as of 2021 and GH Actions warns of some of their commands getting disabled soon, so they were replaced with [softprops/action-gh-release](https://github.com/softprops/action-gh-release), suggested in both original actions' archival message.
=> #81 - Upgrade github actions dependencies

.github/workflows/test.yaml
Resolves #66
Enable running android instrumented tests using [ReactiveCircus/android-emulator-runner](https://github.com/ReactiveCircus/android-emulator-runner).
Also add matrix checks to run tests on multiple API levels, right now 19 (enioka scan min version) and 28 (enioka scan target version).
Old workflow runtime: ~3min
New workflow runtime: ~9min
=> #66 - Run integration tests in pipeline

enioka_scan/src/main/java/com/enioka/scanner/activities/ScannerCompatActivity.java, enioka_scan/src/main/java/com/enioka/scanner/camera/CameraBarcodeScanViewBase.java, enioka_scan/src/main/java/com/enioka/scanner/camera/CameraBarcodeScanViewV1.java, enioka_scan/src/main/java/com/enioka/scanner/camera/CameraBarcodeScanViewV2.java, enioka_scan/src/main/java/com/enioka/scanner/camera/TargetView.java, enioka_scan/src/main/res/layout/activity_main_alt.xml, enioka_scan/src/main/res/values-fr/strings.xml, enioka_scan/src/main/res/values/attrs.xml, enioka_scan/src/main/res/values/strings.xml
Resolves #91 
- Add pause toggle to camera view in default activity, hooked to camera's `pauseCamera()`/`resumeCamera()` methods.
- Differentiate target color in Active / Paused variants, defaults to RED for active and GRAY for paused.
- Add pause/resume methods to `TargetView` to change the target color when called by the `CameraBarcodeScanView`
=> #91 - Change target color when camera is paused

README.md, enioka_scan/src/main/java/com/enioka/scanner/camera/CameraBarcodeScanViewBase.java, enioka_scan/src/main/java/com/enioka/scanner/camera/CameraBarcodeScanViewV1.java, enioka_scan/src/main/java/com/enioka/scanner/camera/CameraBarcodeScanViewV2.java
Resolves #86 
Resolves #87 
- Make Camera2 autofocus zone match the target rectangle (was previously a square at the center of the screen)
- Make Camera1 & 2 autofocus zone "follow" the target whenever moved or tapped (it will trigger a re-focus on the target rectangle)
=> #86, #87 - Improve autofocus on target

enioka_scan/src/main/java/com/enioka/scanner/camera/CameraBarcodeScanViewV1.java, enioka_scan/src/main/java/com/enioka/scanner/camera/CameraBarcodeScanViewV2.java
While the method would work when called from a button on the activity, it would cause a crash if called from the code. The calls to targetView are now done on the UI thread.
=> Fix target pausing call to UI thread

build.gradle, demoscannerapp/build.gradle, enioka_scan/build.gradle, enioka_scan_honeywell/build.gradle, enioka_scan_koamtac/build.gradle, enioka_scan_m3/build.gradle, enioka_scan_mock/build.gradle, enioka_scan_zebra/build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties
Update Gradle dependencies to latest Android Studio stable release specs (Giraffe | 2022.3.1).
Also replace deprecated `compileSdkVersion` keyword with `compileSdk`.
=> Update gradle to 8.1

enioka_scan/src/main/java/com/enioka/scanner/activities/ScannerCompatActivity.java, enioka_scan/src/main/java/com/enioka/scanner/sdk/zebraoss/commands/Ack.java, enioka_scan/src/main/java/com/enioka/scanner/sdk/zebraoss/ssi/SsiCommand.java, enioka_scan/src/main/java/com/enioka/scanner/sdk/zebraoss/ssi/SsiParser.java
Resolves #110 
Use HOST_ACK (0x96) instead of CMD_ACK (0xD0) if the scanner replies to the INIT_COMMAND (0x90) with a 0x91 response.
If ignored and CMD_ACK is used, the device would lock itself for a few seconds after each action while awaiting for the HOST_ACK that never comes. This change fixes that problem and the scanner becomes available again immediately after a successful scan.
Also fix the handling of scanner search options handling in `ScannerCompatActivity` where settings from the intent that started the activity would be overridden by defaults, meaning Bluetooth would always be disabled during the search.
=> #110 - Add support for HOST_ACK to SSI parser

enioka_scan/src/main/java/com/enioka/scanner/camera/CameraBarcodeScanViewBase.java, enioka_scan/src/main/java/com/enioka/scanner/camera/CameraBarcodeScanViewV1.java, enioka_scan/src/main/java/com/enioka/scanner/camera/Resolution.java, enioka_scan/src/main/java/com/enioka/scanner/camera/ViewHelpersResolution.java, enioka_scan/src/main/res/layout/activity_main_alt.xml, enioka_scan/src/main/res/values/attrs.xml
Resolves #84 
- Remove device-specific hacks in CameraV1.
As no crash or performance reduction was observed when removing the hacks, I assume the original purpose was to stop the adaptive resolution from being called repeatedly until the minimum resolution was reached, as lower resolutions do not seem to improve performance on these devices. To solve this, a minimum resolution is now enforced (720px minimum on the Y axis) below which the preview is considered unusable anyway (though 480px would likely still be fine). This means even if the adaptive resolution is called over and over, it will stop at a much more reasonable point.
Tested with SPA43LTE, no access to LG-H340n or Archos Sense 50X currently.
- No device-specific hacks were found in CameraV2.
=> #84 - Remove device-specific camera hacks

enioka_scan/src/main/java/com/enioka/scanner/camera/CameraBarcodeScanViewV1.java, enioka_scan/src/main/java/com/enioka/scanner/camera/CameraBarcodeScanViewV2.java
Add checks for null attributes in Camera V1/V2 methods. Once reached, instead of crashing the method will simply do nothing.
Related to:
- #134 
- #135
- #136 (likely)
- #138 
- #139
- #140 
- #141
It is important to note that these attributes can only become null when manually set that way through closing methods, or when automatically cleaned during the normal Android lifecycle, so reaching these guards is equivalent to a "use after free".
Most of the crashes observed in the issues could not be replicated.
=> Add safeguards for null camera attributes

enioka_scan/src/main/java/com/enioka/scanner/camera/CameraBarcodeScanView.java, enioka_scan/src/main/java/com/enioka/scanner/camera/CameraBarcodeScanViewBase.java
#148
Camera View now has a public method (unused by default) to reset the position of the target.
=> #148 - Add target reset function to camera view

enioka_scan/src/main/java/com/enioka/scanner/camera/ViewHelpersResolution.java
#150 
Fix handling of portrait/landscape orientations in resolution helper, and prevent using resolutions that are higher than the available space.
While this does not affect the preview in `fillAvailableSpace` mode besides the resolution cap (this mode still stretches by design), this ***should*** (it did when tested) prevent the `fitToPicture` mode from stretching/flattening while it tries to fit inside the view using a combination of higher resolution and different aspect ratio.
=> #150 - No longer allow resolutions higher than device display

enioka_scan/src/main/java/com/enioka/scanner/camera/CameraBarcodeScanViewV2.java
#149 
To prevent crashes in case the camera activity is being destroyed while the init process is being run in parallel, the `OnConfigure` callback is now wrapped in a try/catch expecting NullPointerExceptions generated by attributes no longer being available.
=> #149 - Wrap CV2's OnConfigred in a try/catch

enioka_scan/src/main/java/com/enioka/scanner/sdk/zebraoss/ZebraOssScanner.java
#160 
Call command to enable all symbologies on ZebraOSS devices (no option to use a specific list, either all or nothing).
Warning: could not be tested on an actual device (dead battery).
=> #160 - Force-enable all symbologies for ZebraOSS

enioka_scan_zebra_dw/src/main/java/com/enioka/scanner/sdk/zebra/dw/ZebraDwScanner.java
NPE could happen if no `illumination_mode` parameter was present in the config.
=> Fix NPE for DW sdk during illumination config #162

.github/workflows/release.yaml, .github/workflows/test.yaml
Mainly to upgrade the `gradle-build-action` which was vulnerable. Also upgrade other actions while we're at it.
=> Upgrade github actions

enioka_scan_zebra_dw/src/main/java/com/enioka/scanner/sdk/zebra/dw/ZebraDwScanner.java, enioka_scan_zebra_dw/src/main/java/com/enioka/scanner/sdk/zebra/dw/ZebraDwSymbology.java
#169 
#172 
Attempt to fix DW-related problems, most likely linked to profile handling.
- paused Scanner still received and handled intents, which could generate config loops and lower performances, now the receiver returns immediately if the scanner is paused
- wrong intent was called during pause/resume lifecycle steps, now disables the profile's scanning instead of datawedge as a whole
- add missing QRCODE and AZTEC symbologies to the DW symbology list
=> Fix/Optimize ZebraDwScanner lifecycle and intent handling

enioka_scan_zebra_dw/src/main/java/com/enioka/scanner/sdk/zebra/dw/ZebraDwScanner.java
Until now the active profile was only checked for PROFILE_SWITCH notifications, so if for any reason the profile changed silently it would not be detected by the app. Now every notification will be checked, this may cause more switch requests than necessary but it should at least prevent getting locked out of the wanted profile until the next resume() call.
=> Add DW profile check on every notification #172

.github/workflows/test.yaml
- Switch GitHub action runner from MacOS to Ubuntu, in order to have an x86-64 architecture instead of ArmV8 (see https://github.com/AntennaPod/AntennaPod/pull/7140).
=> 178 - CI: integration tests no longer work, adb cannot find the emulator

enioka_scan_camera/src/main/java/com/enioka/scanner/sdk/camera/CameraBarcodeScanViewV2.java
The problem was that sometimes `onMeasure()` was being called after the preview was initialized, so the `startPreview()` call in the `surfaceChanged()` method would not do anything.
The only way to force an update of the preview resolution is to pause and resume it, so the capture session is destroyed and can be properly recreated with the new resolutions.
This adds the issue of concurrent calls to `startPreview()`, some which are actually needed to create the base preview or update the resolution, while others are not. As we cannot create multiple captureSessions, we have to wait for the ongoing init to finish before destroying the session and calling the method again with more up-to-date parameters (via pause-resume).
=====
This fix is a bit of a hack with regards to its handling of …
=> #150 - Force reinit of camera2 view on surface change

demoscannerapp/src/main/java/com/enioka/scanner/demo/WelcomeActivity.java, enioka_scan/src/androidTest/java/com/enioka/scanner/service/ScannerServiceAndroidTest.java, enioka_scan/src/main/java/com/enioka/scanner/service/ScannerService.java
https://github.com/enioka-Haute-Couture/enioka_scan/issues/168
- Remove explicit intent when `ScannerSearchOptions` can be used.
=> 168 - Refactor code to better account for new ScannerSearchOptions

docs/api/camera.md, enioka_scan/src/main/java/com/enioka/scanner/sdk/camera/CameraScannerProvider.java, enioka_scan_camera/src/main/java/com/enioka/scanner/sdk/camera/CameraBarcodeScanView.java, enioka_scan_camera/src/main/java/com/enioka/scanner/sdk/camera/CameraBarcodeScanViewBase.java, enioka_scan_camera/src/main/java/com/enioka/scanner/sdk/camera/CameraProvider.java
https://github.com/enioka-Haute-Couture/enioka_scan/issues/188
Add two functions to `CameraBarcodeScanView`:
- `setTargetPosition`: Allows you to manually set the upper `y` coordinates of the target rectangle.
- `setTargetDimension`: Allows you to manually define the width and height of the target rectangle.
=> 188 - Allow moving and resizing target from code

enioka_scan_camera/src/main/java/com/enioka/scanner/sdk/camera/ZXingFrameAnalyser.java
https://github.com/enioka-Haute-Couture/enioka_scan/issues/195
- On `Zxing` frame analyzer, check that `this.scanner` instance is correctly init (not `null`) before settings hints.
=> fix: Check that Zxing scanner is init before setting hints

enioka_scan_camera/src/main/java/com/enioka/scanner/sdk/camera/CameraBarcodeScanView.java, enioka_scan_camera/src/main/java/com/enioka/scanner/sdk/camera/CameraBarcodeScanViewBase.java, enioka_scan_camera/src/main/java/com/enioka/scanner/sdk/camera/CameraBarcodeScanViewScanner.java, enioka_scan_camera/src/main/java/com/enioka/scanner/sdk/camera/CameraBarcodeScanViewV1.java, enioka_scan_camera/src/main/java/com/enioka/scanner/sdk/camera/CameraBarcodeScanViewV2.java
https://github.com/enioka-Haute-Couture/enioka_scan/issues/204
- When initializing the camera, check whether the camera preview surface has not been destroyed. In this case, reset it to display the camera preview correctly.
=> 204 -  Camera preview freezes on the demo-app

.github/workflows/release.yaml, fastlane/Fastfile
It turns out the signing config is required even for the regular `build` command otherwise it will refuse to build.
=> Release v3: fix release workflow build step
